name: weather_demo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # the data layer, any API call or storage call should be there
  data_repository:
    path: packages/data_repository

  # https://pub.dev/packages/bloc
  # used by the UI to handle state
  bloc: ^8.1.0

  # https://pub.dev/packages/flutter_bloc
  # used by the UI to handle state
  flutter_bloc: ^8.1.1

  # https://pub.dev/packages/go_router
  # used as a router lib
  go_router: ^10.0.0

  # https://pub.dev/packages/simple_animations
  simple_animations: ^5.0.0+3

  # https://pub.dev/packages/supercharged
  supercharged: ^2.1.1

  # https://pub.dev/packages/google_fonts
  # used to set custom fonts
  google_fonts: ^5.1.0

  # https://pub.dev/packages/either_dart
  either_dart: ^1.0.0

  # https://pub.dev/packages/lottie
  lottie: ^2.5.0

  # https://pub.dev/packages/intl
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
